name: Node.js frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: frontend

jobs:
  lint-and-format:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.next
        key: ${{ runner.os }}-build-${{ cache-next-build }}-${{ hashFiles('**/yarn.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ cache-next-build }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: npm install -g yarn
    - run: yarn
    - run: yarn format
    - run: yarn lint
    - run: yarn build
#   Run test
#   - run: yarn test
